### PR TITLE
Adding titles to cartoons

### PR DESCRIPTION
**Pull request by jclagarde**
Hello! Please let me know how these titles for the cartoons sound and if I should change the wording, placement, font size, etc for any of them. Thank you!

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Thanks, JC. Figure 4 did not have a title, and figure 5 looks like this:
image

Figure S1:
image

The text seems extended and discrete! Could you fix it?

**Comment by Farnazmdi** [comment]
@jclagarde I updated the cartoons. Could you do `git pull` and then re-run figure5, S01--S010?

**Comment by jclagarde** [comment]
> @jclagarde I updated the cartoons. Could you do `git pull` and then re-run figure5, S01--S010?

Thank you! And sure thing, I will do that today. Also, were you able to find out what was causing the text to be broken?

**Comment by Farnazmdi** [comment]
Thanks! I am not sure, maybe because the window you had that you were writing the title on, was longer than the length of the title string... I am not sure really...

**Comment by jclagarde** [comment]
> Thanks! I am not sure, maybe because the window you had that you were writing the title on, was longer than the length of the title string... I am not sure really...

Ah I see. I just realized that I also used this font called 'deja vu sans' that not everyone has on their computer so that may have been a possible cause as well

**Comment by Farnazmdi** [comment]
Also, please remove "fig4title1.svg" and "fig4title2.svg" in the cartoon folder.

**Review by Farnazmdi — APPROVED** [review]
Great! I think now the figures are in better shape!

**Comment by jclagarde** [comment]
@aarmey Hi Dr. Meyer, when you're able to, can you look over the edited cartoons for figure 4, 5, and S01-S10? If everything looks good, please merge the PR

**Pull request merged**
