### PR TITLE
edited dead cells in cartoon 

### PR DESCRIPTION
**Pull request by jclagarde**
Hi! When you get the chance, please look over the edits I made to the cartoons containing dead cells (figure 4, S03, S05, S07, and S10). Please let me know if there are any further edits I should make. Thank you!

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
Thanks JC. For dead cells, we should show a cell but then have an X over it. In the present setup, it kind of looks like cells divide into a single cell when one of them dies. In other words, it looks like the dead cell never exists in the first place.

**Comment by jclagarde** [comment]
> Thanks JC. For dead cells, we should show a cell but then have an X over it. In the present setup, it kind of looks like cells divide into a single cell when one of them dies. In other words, it looks like the dead cell never exists in the first place.

**Comment by jclagarde** [comment]
> Thanks JC. For dead cells, we should show a cell but then have an X over it. In the present setup, it kind of looks like cells divide into a single cell when one of them dies. In other words, it looks like the dead cell never exists in the first place.

Thanks for the suggestion. Just to clarify, should the cell that the X is over still be left as a red cell or should it be placed over a green or blue cell such as the ones below?
Screen Shot 2021-06-18 at 11 02 12 AM
Screen Shot 2021-06-18 at 11 02 22 AM

**Comment by jclagarde** [comment]
I included the cells with the X over the dead ones. Please let me know how it looks and if I should make any further edits. Thank you!

**Review by Farnazmdi — APPROVED** [review]
Looks good to me, thanks!

**Comment by jclagarde** [comment]
> Looks good to me, thanks!

Sounds good!

**Comment by jclagarde** [comment]
@aarmey Hi Dr. Meyer, when you get the chance, please look over the changes I made. If it looks good to you, please merge this PR. Thank you!

**Comment by aarmey** [comment]
Great, thanks!

**Pull request merged**
