### PR TITLE
Cross validation with equal transitions

### PR DESCRIPTION
**Pull request by Farnazmdi**
1. To have equal transitions between the states (and not estimating the T), in BaumWelch.py, during the M step, the transition probabilities are set manually according to the number of states. (only one line is added, and line 89 is commented to prevent the T estimation).
Other changes are some clean ups.
2. The function that is used for performing the cross-validation and finding the likelihood of masked observations (output_LL) is moved to the crossval.py 
3. figure 19 is the figure where we perform cross validation on synthetic data.
4. figure 21 is the figure we perform cross validation on experimental data.

### CODE REVIEW

**Comment by aarmey** [comment]
@Farnazmdi is this something that should eventually be merged or deleted?

**Comment by Farnazmdi** [comment]
There is an underflow error here in calculating the gamma likelihood:
`outt -= np.sum(gammas[i][jidx] * np.log(gamP))`
FloatingPointError: underflow encountered in multiply
in gamma_LL line 65.

@aarmey Do you have an idea about how to address this? It is already in log format..

**Comment by aarmey** [comment]
I made a small adjustment that I *think* will fix the issue. Let me know if it still errors.

**Comment by Farnazmdi** [comment]
Thank you, it is fixed.

**Comment by Farnazmdi** [comment]
This should be ready to merge.

**Comment by aarmey** [comment]
Great. Merging.

**Pull request merged**
