### PR TITLE
MCF10A data import

### PR DESCRIPTION
**Pull request by Farnazmdi**

### CODE REVIEW

**Comment by Farnazmdi** [comment]
EGF and HGF have some sort of error yet... I will have to investigate. Will do it tomorrow.

**Comment by Farnazmdi** [comment]
@aarmey A problem in the data: apparently, one cell has 3 daughter cells in EGF treatment data... I am not sure what to do with this. Should I just ignore the third one?
image

**Comment by aarmey** [comment]
Ignore the third one for now and then we can ask about this.

**Comment by Farnazmdi** [comment]
There were some other data issues, I found another cell with three children in HGF treatment file, and another error was that one cell had 1 child.
I wrote some assertions and if-else statements.
One thing I don't know is the concentration of these drugs. Do we only have one concentration of each drug?

**Comment by Farnazmdi** [comment]
At first I tried to use one function to import both cell lines, but they suffer from different data errors.. so I decided to separate them. I will work on a function that can import both cell lines later if it is alright.. I figured time is of the essence now!

**Comment by aarmey** [comment]
> There were some other data issues, I found another cell with three children in HGF treatment file, and another error was that one cell had 1 child.

I'd suggest throwing out lineages with these problems right now, but print out a warning. We can ask about fixing these problems.

> I wrote some assertions and if-else statements.
> One thing I don't know is the concentration of these drugs. Do we only have one concentration of each drug?

These are growth factors. They were applied at only one concentration.

**Comment by aarmey** [comment]
Completely agree with your choice to just keep these imports separate.

**Review by aarmey — APPROVED** [review]
Looks good.

**Pull request merged**
