### PR TITLE
Manuscript update

### PR DESCRIPTION
**Pull request by jclagarde**
I read through the manuscript and fixed any typos I saw!
I had a question though, sometimes 'Bernoulli' is capitalized and some times it is not, same with 'gamma' and 'lapatinib'. I can go ahead and change it, just let me know which is preferred! :)

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Thanks very much, it is great! I think you only need Bernoulli and Gamma capitalized among them.

**Comment by Farnazmdi** [comment]
It helps if you check for other mistakes like if a figure doesn't have a subplot character (a,b,c,...) or if some sentence is off.

**Review by Farnazmdi — APPROVED** [review]

**Comment by jclagarde** [comment]
no problem! and sounds good, I will take a closer look at those areas, most likely sometime tomorrow morning!

**Comment by Farnazmdi** [comment]
@jclagarde  is this PR done?

**Comment by jclagarde** [comment]
@Farnazmdi Yes! I will start a new PR when I start with the captions for the supp figures

**Pull request merged**
