### PR TITLE
Supplementary Figures Captions Edit

### PR DESCRIPTION
**Pull request by jclagarde**
Hello! 

I edited the captions on the supplementary figures. Please let me know if there are any further revisions I should make!

### CODE REVIEW

**Comment by Farnazmdi** [comment]
@jclagarde Hey, what are the new figures that have been added to the repo?

**Comment by Farnazmdi** [comment]
Never mind, I deleted them. I think you have a very old version of the repo in your local!
I would clone it again in another folder.

**Review by Farnazmdi — APPROVED** [review]
Looks good! Thanks.

**Comment by jclagarde** [comment]
@Farnazmdi Ah, I'm sorry about that! Thank you for letting me know and for deleting the old figures

**Pull request merged**
