### PR TITLE
edited cartoons for supplementary figures S08, S09, and S10

### PR DESCRIPTION
**Pull request by jclagarde**
I noticed that the cartoon for supplementary figure S10 is blocking the letter 'd' on the other subfigure for S10. I resized and re-centered it as well as for supplementary figures S08 and S09. However, when I tried to build figure S10, I kept getting this error (but not when I tried building the other figures). I wasn't sure if it was just my computer or not 

Screen Shot 2021-04-23 at 3 45 37 PM

### CODE REVIEW

**Comment by Farnazmdi** [comment]
That's okay. Don't worry about the warning.

**Review by Farnazmdi — APPROVED** [review]
Figures look good, thanks!

**Comment by aarmey** [comment]
@jclagarde doesn't look like you've replaced S10 here?

**Comment by jclagarde** [comment]
@aarmey I tried to re-scale the cartoon and center it. I'm having trouble building figure S10 on my computer though. Is there another way to view its build on this specific branch?

**Comment by jclagarde** [comment]
@aarmey Actually, it did build, it just took a while. But this is what figure S10 should look like now on this branch. Is that not what you see on your end?
Screen Shot 2021-04-23 at 4 58 30 PM

**Comment by aarmey** [comment]
Great!

**Pull request merged**
