### PR TITLE
transition matrix figure

### PR DESCRIPTION
**Pull request by Farnazmdi**
@aarmey I have the same problem as JC's PR. But I haven't cloned the repo inside itself.

### CODE REVIEW

**Comment by aarmey** [comment]
It's because as soon as that build fails in that way, the build server doesn't know how to remove the submodule. I'll clean it out.

**Comment by Farnazmdi** [comment]
Thank you very much.

**Review by aarmey — CHANGES_REQUESTED** [review]
We need to add arrows indicating when a state stays itself.

**Comment by Farnazmdi** [comment]
Actually, that's what I'm struggling with right now. It looks like `draw_networkx_edges` doesn't do that. I'll look more.

**Comment by aarmey** [comment]
Darn. Looks like it is indeed not an option. In that case I think we're stuck using graphviz.

**Comment by Farnazmdi** [comment]
:-( Should I save the `.svg` and overlay on the manuscript?

**Comment by aarmey** [comment]
Yep

**Pull request closed without merging**
