### PR TITLE
embed lineage plots in the figures

### PR DESCRIPTION
**Pull request by Farnazmdi**
Figure 1 and figure 4 were modified based on issue #524.
The difference is that I couldn't rotate them. If you think they might not be suitable in terms of their height and length in the paper, please let me know @aarmey.

### CODE REVIEW

**Comment by aarmey** [comment]
How about something like this? https://stackoverflow.com/questions/22540449/how-can-i-rotate-a-matplotlib-plot-through-90-degrees

**Comment by aarmey** [comment]
Actually, I like them better in their orientation here. I think it makes sense for the x-axis to be time.

**Comment by Farnazmdi** [comment]
image
They show up for me, are you referring to something else? (I only kept 2 trees of censored and 2 of uncensored to save up some space, they used to be 3.)

**Comment by aarmey** [comment]
You're right. Can't find the missing one now...

**Pull request merged**
