### PR TITLE
Manuscript edits

### PR DESCRIPTION
**Pull request by jclagarde**
I put the whole manuscript through Grammarly and tried to edit any grammatical errors I saw! Please let me know if any additional changes should be made :) 

Also I noticed that there are merge conflicts in the files. I don't see any merge heads on my remote branch. Would it be okay to just press 'resolve conflict' ?

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Great work! Thanks, JC.
I think when you started working on this branch you hadn't pulled the changes, the conflict is because of aarmey's changes yesterday.
Yes! If you press "resolve conflicts" it will take you through those lines that have conflicts and you can choose which line to keep; the one that is on your branch or the one on master.
I would suggest keeping things on master because aarmey has gone through them and they are less likely to be erroneous.

To resolve the conflicts, you see `<<<<<<< jc-manuscriptedit` and then some code or text, and then `========` which separates your branch from master and then `>>>>>>> master`.
If you want to keep things from master, among these elements I mentioned you should only keep the content between `======` and `>>>>>>> master` and get rid of the rest. Let me know if you had difficulty resolving the conflicts.

**Comment by jclagarde** [comment]
Okay! I kept the edits on the master branch. Build is still failing however

**Comment by Farnazmdi** [comment]
@aarmey I think `.gitmodule` needs an update. 
image
Should I replace the existing line in `.gitmodule` with `https://github.com/meyer-lab/tHMM.git`?

**Comment by aarmey** [comment]
@jclagarde you cloned the tHMM repo inside of itself. Move these file edits to a new branch without this.

**Pull request closed without merging**
