### PR TITLE
Figs04 05

### PR DESCRIPTION
**Pull request by Farnazmdi**
1. The keyword for `kwargs` for passing `list_of_Ts` in `commonAnalyze` was not correct.
2. changed bernoulli for state 2 from 0.75 to 0.9.
3. T is now only changing from 0.6 to 0.99 and `pi` is being estimated. 
The difference with the previous figure is that we only see half of the previous figure, meaning we see that the proportion of cells in the two states changes from ~60% to ~100% and this results in a slight decrease of accuracy which is expected and I think it makes the point.

### CODE REVIEW

**Comment by Farnazmdi** [comment]
Figure S05:
image

Figure S04:
image

**Comment by Farnazmdi** [comment]
The build fails after 14 seconds... I am not sure what's going on.

**Comment by aarmey** [comment]
Should be fixed. Rerun.

**Review by aarmey — APPROVED** [review]
Check the results once this builds, but if it looks reasonable it should be ready to merge.

**Comment by Farnazmdi** [comment]
Wow! remarkible!
image

**Pull request merged**
