### PR TITLE
Figure update

### PR DESCRIPTION
**Pull request by shak360**

### CODE REVIEW

**Comment by jclagarde** [comment]
@shak360 @Farnazmdi this PR is ready to be merged. I made the font in the figure 5 cartoon larger and made the figures larger horizontally so that the x axis is more legible. I also fixed the figure 3 cartoon and it's positioned correctly now

**Comment by Farnazmdi** [comment]
It looks grrreat! thanks JC!

**Comment by Farnazmdi** [comment]
Figure 6 still doesn't have the caption, not sure why. Maybe Shakthi nows how to fix that.

**Comment by jclagarde** [comment]
> Figure 6 still doesn't have the caption, not sure why. Maybe Shakthi nows how to fix that.

I haven't added the caption for figure 6 in the manuscript yet. Is the figure 6 caption something different?

**Comment by shak360** [comment]
Yea I agree something is wrong with the Figure 6 caption, but we can fix that on a later branch.  Thanks for the work @jclagarde , great stuff. 

A suggestion for the future: try to keep all the fonts Arial (anything sans script should do), but if Arial is available try to use that over other fonts.

I'll merge and delete the branch.

**Pull request merged**
