### PR TITLE
Fm fig2

### PR DESCRIPTION
**Pull request by Farnazmdi**

### CODE REVIEW

**Comment by shak360** [comment]
I think your figure is a cartoon right @Farnazmdi ? I think you linked it to figure2.svg in the output folder and not the one in the cartoons folder, but let me know if that's not what you want.

**Comment by shak360** [comment]
Hmmm, I still can't see the figure in the manuscript for some reason.

**Comment by shak360** [comment]
I approve this PR @Farnazmdi , but can you check again that your figure is showing up in the manuscript? Also the E-step isn't Viterbi, Baum-Welch covers both the M and E step for expectation maximization, but we can fix that on a future branch.

**Comment by Farnazmdi** [comment]
@shak360 is figure 3 still taking a lot of time?

**Comment by Farnazmdi** [comment]
Which one of figure 7 and 8.py is the AIC figure? Both seem to have some component of AIC in them. @shak360

**Comment by shak360** [comment]
No figure 3 isn't in the makefile. Builds only take 15 minutes @Farnazmdi

**Comment by shak360** [comment]
I think I figured out the problem @Farnazmdi . The figure 2 svg is really big. I can only see a small part of the left corner.

**Comment by Farnazmdi** [comment]
Yeah I know. I fixed it but something else was failing.

**Comment by Farnazmdi** [comment]
Generating figure S04 is failing for some reason..

**Comment by shak360** [comment]
OK I'll try to fix figureS04 sorry about that @Farnazmdi . Yea looks like your fixes make figure 2 appear now, great work.

**Comment by shak360** [comment]
@Farnazmdi Looks good to me 🥇 Feel free to merge whenever

**Pull request merged**
