### PR TITLE
figures updated

### PR DESCRIPTION
**Pull request by Farnazmdi**
The figures are updated based on the edit to the limits and now they all start from 0.

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
Should gamma k and theta extend to 0?

**Comment by Farnazmdi** [comment]
I think they were already starting at 0. I don't think it matters. Should I make any changes to it?

**Comment by aarmey** [comment]
No, the y-axis in the figures clearly doesn't extend to 0. Yes, I think it would be helpful to do this.

**Comment by Farnazmdi** [comment]
The gamma parameters in supp figures now are in the range of 0 and 20.

**Review by aarmey — APPROVED** [review]

**Pull request merged**
